export const sampleChats = [{
    avatar: '',
    name: "Jhon Doe",
    _id: 1,
    groupChat: false,
    sameSender: false,
    isOnline: true,
    LastMessage: "hello"
}]

export const sampleData = [
    {
        name: "Chinki",
        _id: 1,
        avatar: "https://i.pinimg.com/474x/0c/8c/f9/0c8cf95179609df437c9684bc19352fb.jpg",
        isOnline: true,
        lastMessage: "hello!",
        newMessagesAlert: 0,
    },
    {
        name: "Pintu",
        _id: 2,
        isOnline: false,
        lastMessage: "hemlo",
        newMessagesAlert: 2,
    },
    {
        name: "Vada Pav",
        _id: 3,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 4,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 5,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 6,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 7,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 8,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 9,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 10,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 11,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
    {
        name: "Vada Pav",
        _id: 12,
        avatar: "https://play-lh.googleusercontent.com/HnzbI7urJlB6V26dtKiawYoBrH4iR5DAAk4KqNZzIa0NRWQukskR6aX7IrV55AULKIgA=w240-h480-rw",
        isOnline: true,
        lastMessage: "send money",
        newMessagesAlert: 4,
    },
]